export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const INCREASE_QUANTITY_IN_CART = "INCREASE_QUANTITY_IN_CART";
export const DECREASE_QUANTITY_IN_CART = "DECREASE_QUANTITY_IN_CART";

export const TRY_AT_HOME_CART = "TRY_AT_HOME_CART";
export const BUY_NOW_HOME_CART = "BUY_NOW_HOME_CART";
